# Generated by Django 6.0.1 on 2026-02-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(choices=[('Perro', 'perro'), ('Gato', 'gato')], max_length=20)),
            ],
        ),
    ]
