# Generated by Django 6.0.1 on 2026-02-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('Gato', 'gato'), ('Perro', 'perro')], max_length=20),
        ),
    ]
