# Generated by Django 6.0.1 on 2026-02-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_api', '0006_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('Perro', 'perro'), ('Gato', 'gato')], max_length=20),
        ),
    ]
